### ISSUE TITLE
Prims algorithm(c programming)

### ISSUE THREAD

**Issue by Vrushti24** [Sniper7sumit/Hacktoberfest2021#256]
Write a program to implement Prims algorithm for Minimum Spanning Tree

Please assign me this !! @Sniper7sumit

**Comment by 2309harshit** [comment]
Hey can you please assign this issue to me. I think I can do this in c++.
Thanks in anticipation!

**Comment by Vrushti24** [comment]
Raised PR #259 please merge it Thank you @Sniper7sumit

**Comment by Sniper7sumit** [comment]
> Raised PR #259 please merge it Thank you @Sniper7sumit

Done

**Comment by Vrushti24** [comment]
Thank you @Sniper7sumit
