### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by amiteshag320** [Sniper7sumit/Hacktoberfest2021#267]
I will write a code to solve a dynamic programming problem named Longest Palindromic Substring , with proper comments , TC , SC and example.
Please Assign this issue to me .
Thanks !!

**Comment by harsh6975** [comment]
The longest Palindromic Substring can be solved without using dynamic problem. So we can even optimize space complexity. 
I will explain the intuition behind it, time complexity with proper comments.
please assign me
Thanks

**Comment by harsh6975** [comment]
The longest Palindromic Substring can be solved without using dynamic problem. So we can even optimize space complexity.
I will explain the intuition behind it, time complexity with proper comments.
Please assign me
Thanks
