### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Sniper7sumit** [Sniper7sumit/Hacktoberfest2021#275]
**Can someone update README.md in a best way which looks like attractive ******

**Comment by absolute-looser** [comment]
Hey can you assign this to me.

**Comment by Chayan-11** [comment]
Hey @Sniper7sumit updated the readme file #285.

**Comment by Sniper7sumit** [comment]
Thanks 😊

**Comment by Sniper7sumit** [comment]
> Hey @Sniper7sumit updated the readme file #285.

Thanks 😊
