### ISSUE TITLE
stringstream

### ISSUE THREAD

**Issue by krishnendusukumar** [Sniper7sumit/Hacktoberfest2021#393]
https://www.hackerrank.com/challenges/c-tutorial-stringstream/problem?isFullScreen=true
Please assign this to me, as I am able t code this.

**Comment by Vrushti24** [comment]
Why is this project excluded from Hacktoberfest? @Sniper7sumit

**Comment by Sniper7sumit** [comment]
I also don't know why this Happens i think someone report the repo due to high merging of pr ..There is many pr this year which excluded from Hacktoberfest

**Comment by Vrushti24** [comment]
So is there any chance it will be reconsidered? @Sniper7sumit
