### ISSUE TITLE
I have faced cloning issue.

### ISSUE THREAD

**Issue by mohitCodepy** [Sniper7sumit/Hacktoberfest2021#470]
after cloning I haven't got updated javascript and data structure folders, I got only single file in js and less files in data structures.
my main branch contains correct code but my 2nd branch not.

$ git clone https://github.com/mohitCodepy/Hacktoberfest2021.git .
Cloning into '.'...
remote: Enumerating objects: 2314, done.
remote: Counting objects: 100% (1624/1624), done.
remote: Compressing objects: 100% (1026/1026), done.
remote: Total 2314 (delta 834), reused 1321 (delta 587), pack-reused 690
Receiving objects: 100% (2314/2314), 848.87 KiB | 890.00 KiB/s, done.
Resolving deltas: 100% (932/932), done.
error: invalid path 'Data Structure Algorithms/https:/github.com/Roundrobin.c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by saurabhtopthon01** [comment]
According to the contribution guide you have to make a new branch, make some changes and then push it. After that you can make a pull request.
