### ISSUE TITLE
Update STL vector.cpp file

### ISSUE THREAD

**Issue by saurabhtopthon01** [Sniper7sumit/Hacktoberfest2021#472]
Hi @Sniper7sumit can i update vector.cpp file in STL folder. I can add more functions related to vector STL .

**Comment by kpratyush12345** [comment]
HI @Sniper7sumit can i Update the vector.cpp file , I will add all the STL functions with comments and examples.

**Comment by kpratyush12345** [comment]
Sorry @Sniper7sumit  can u please assign me again it got clicked by mistake
