### ISSUE TITLE
 currency convertor

### ISSUE THREAD

**Issue by Amadabh** [Sniper7sumit/Hacktoberfest2021#488]
I would like to add currency convertor @Sniper7sumit  for hacktoberfest

**Comment by Sniper7sumit** [comment]
> I would like to add currency convertor @Sniper7sumit for hacktoberfest

This repo is excluded from hacktoberfest due to spam pr's

**Comment by DavidMaged171** [comment]
I can solve this problem using c++, please assign it to me.
